Update action.yml

diff --git a/.github/actions/setup-susfs/action.yml b/.github/actions/setup-susfs/action.yml
--- a/.github/actions/setup-susfs/action.yml
+++ b/.github/actions/setup-susfs/action.yml
@@ -13,6 +13,8 @@ runs:
           -b gki-android12-5.10 \
           susfs
 
+        test -d susfs/kernel_patches || (echo "SUSFS repo invalid"; exit 1)
+
         SUSFS_VERSION=$(grep SUSFS_VERSION susfs/kernel_patches/include/linux/susfs.h | cut -d' ' -f3 | tr -d '"')
         echo "SUSFS_VERSION=$SUSFS_VERSION" >> $GITHUB_ENV
 
@@ -21,11 +23,16 @@ runs:
       run: |
         set -e
 
+        test -d ../../susfs/kernel_patches/fs
+        test -d ../../susfs/kernel_patches/include/linux
+
         cp -r ../../susfs/kernel_patches/fs/* fs/
         cp -r ../../susfs/kernel_patches/include/linux/* include/linux/
         cp ../../susfs/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch ./
 
-        patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch || true
+        patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
+
+        test -f fs/susfs.c || (echo "SUSFS patch failed"; exit 1)
 
     - shell: bash
       working-directory: gki/common
@@ -34,24 +41,32 @@ runs:
 
         DEFCONFIG="arch/arm64/configs/gki_defconfig"
 
-        echo "CONFIG_KSU_SUSFS=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSTAT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$DEFCONFIG"
-        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$DEFCONFIG"
+        append_if_missing() {
+          KEY="$1"
+          VALUE="$2"
+          grep -q "^$KEY=" "$DEFCONFIG" || echo "$KEY=$VALUE" >> "$DEFCONFIG"
+        }
+
+        append_if_missing CONFIG_KSU_SUSFS y
+        append_if_missing CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT y
+        append_if_missing CONFIG_KSU_SUSFS_SUS_PATH y
+        append_if_missing CONFIG_KSU_SUSFS_SUS_MOUNT y
+        append_if_missing CONFIG_KSU_SUSFS_SUS_KSTAT y
+        append_if_missing CONFIG_KSU_SUSFS_SPOOF_UNAME y
+        append_if_missing CONFIG_KSU_SUSFS_ENABLE_LOG y
+        append_if_missing CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS y
+        append_if_missing CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG y
+        append_if_missing CONFIG_KSU_SUSFS_OPEN_REDIRECT y
+        append_if_missing CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSTAT y
+        append_if_missing CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT y
+        append_if_missing CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT y
+        append_if_missing CONFIG_KSU_SUSFS_TRY_UMOUNT y
 
     - shell: bash
       working-directory: gki/common
       run: |
         set -e
 
-        sed -i 's/#ifdef CONFIG_KSU_SUSFS_SPOOF_UNAME/#if 0/' drivers/kernelsu/supercalls.c || true
+        if [ -f drivers/kernelsu/supercalls.c ]; then
+          sed -i 's/#ifdef CONFIG_KSU_SUSFS_SPOOF_UNAME/#if 0/' drivers/kernelsu/supercalls.c
+        fi
